services:
  gcs:
    container_name: gcs
    image: fsouza/fake-gcs-server
    restart: unless-stopped
#    command: -scheme http -backend filesystem -port 4443 -public-host 0.0.0.0:4443 -external-url gcs:4443
    command: -scheme http -backend filesystem -port 4443 -public-host gcs:4443 -external-url http://gcs:4443
    hostname: gcs
    ports:
      - "4443:4443"
    volumes:
#      - ${PWD}/fs/volumes/gcs:/data # uncomment to initialize ETL without using Coingecko API
      - ${PWD}/fs/volumes/gcs-storage:/storage
    networks:
      - storage
    healthcheck:
      test: [ 'CMD-SHELL', 'wget --no-verbose --tries=1 --spider localhost:4443/_internal/healthcheck || exit 1' ]
      interval: 30s
      timeout: 20s
      retries: 3
  etl:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: etl
    env_file:
    - clickhouse.env
    - container.env
    networks:
      - analytics
      - storage
    depends_on:
      clickhouse:
        condition: service_healthy
      gcs:
        condition: service_healthy
  clickhouse:
    image: clickhouse/clickhouse-server:24.6.2.17-alpine
    container_name: clickhouse
    hostname: clickhouse
    env_file: clickhouse.env
    networks:
      - analytics
    restart: unless-stopped
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - ${PWD}/fs/volumes/clickhouse/clickhouse-server:/etc/clickhouse-server/config.d
      - ${PWD}/fs/volumes/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ${PWD}/fs/volumes/clickhouse/errors:/var/log/clickhouse-server
    healthcheck:
      test: clickhouse-local -q 'select 1;'
      interval: 2s
      timeout: 60s
      retries: 20
      start_period: 5s
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144

networks:
  storage:
    name: storage
  analytics:
    name: analytics
