services:
  etl:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
    - clickhouse.env
    - .env
#    hostname: etl
    network_mode: service:clickhouse
    depends_on:
      clickhouse:
        condition: service_healthy
#    command: sleep infinity
  clickhouse:
    image: clickhouse/clickhouse-server:24.6.2.17
    container_name: clickhouse
    hostname: clickhouse
    volumes:
      - ${PWD}/fs/volumes/clickhouse/etc/clickhouse-server/config.d:/etc/clickhouse-server/config.d
      - ${PWD}/fs/volumes/clickhouse/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ${PWD}/fs/errors:/var/log/clickhouse-server
    healthcheck:
      test: clickhouse-local -q 'select 1;'
      interval: 2s
      timeout: 60s
      retries: 20
      start_period: 5s
    env_file: clickhouse.env
    ports:
      - '8123:8123'
      - '9000:9000'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 262144
        hard: 262144

#networks:
#  default:
#    name: 'clickhouse-net'
#    external: true